pipeline:
  build:
    image: python:${PYTHON_VERSION}
    environment:
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    commands:
      - apt-get update
      - apt-get install -y libxml2-dev libxmlsec1-dev build-essential
      - pip install --upgrade pip setuptools py
      - pip install coveralls requirements-builder
      - requirements-builder -e all,${DATABASE} --level=${REQUIREMENTS} setup.py > .drone-${REQUIREMENTS}-requirements.txt
      - pip install -r .drone-${REQUIREMENTS}-requirements.txt
      - pip install -e .[all,${DATABASE}]
      - sh run-tests.sh
matrix:
  include:
    - DATABASE: sqlite
      SQLALCHEMY_DATABASE_URI: sqlite:///test.db
      PYTHON_VERSION: 2.7
      REQUIREMENTS: min
    - DATABASE: sqlite
      SQLALCHEMY_DATABASE_URI: sqlite:///test.db
      PYTHON_VERSION: 3.5
      REQUIREMENTS: min
    - DATABASE: sqlite
      SQLALCHEMY_DATABASE_URI: sqlite:///test.db
      PYTHON_VERSION: 2.7
      REQUIREMENTS: pypi
    - DATABASE: sqlite
      SQLALCHEMY_DATABASE_URI: sqlite:///test.db
      PYTHON_VERSION: 3.5
      REQUIREMENTS: pypi
    - DATABASE: postgresql
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres@localhost:5432/test
      PYTHON_VERSION: 2.7
      REQUIREMENTS: min
    - DATABASE: postgresql
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres@localhost:5432/test
      PYTHON_VERSION: 3.5
      REQUIREMENTS: min
    - DATABASE: postgresql
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres@localhost:5432/test
      PYTHON_VERSION: 2.7
      REQUIREMENTS: pypi
    - DATABASE: postgresql
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres@localhost:5432/test
      PYTHON_VERSION: 3.5
      REQUIREMENTS: pypi
    - DATABASE: mysql
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://user:pwd@localhost:3306/test
      PYTHON_VERSION: 2.7
      REQUIREMENTS: min
    - DATABASE: mysql
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://user:pwd@localhost:3306/test
      PYTHON_VERSION: 3.5
      REQUIREMENTS: min
    - DATABASE: mysql
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://user:pwd@localhost:3306/test
      PYTHON_VERSION: 2.7
      REQUIREMENTS: pypi
    - DATABASE: mysql
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://user:pwd@localhost:3306/test
      PYTHON_VERSION: 3.5
      REQUIREMENTS: pypi
services:
  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
  mysql:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=user
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=pwd
  cache:
    image: redis
